database:
  host: 'hostname'
  user: 'username'
  pass: 'password'
  name: 'db_name'

routes:
  home:
    uri: /
    template: default:home
    title: Home Page
  contact:
    uri: /contact
    template: default:contact
    title: Get in Touch